import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { CopilotKit } from "@copilotkit/react-core";
import "@copilotkit/react-ui/styles.css";
import ClientWrapper from "@/components/ClientWrapper"; // we'll create this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "iTodo - the last todo app you'll ever need",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <ClientWrapper>
          <CopilotKit publicApiKey="ck_pub_bb4179a23020b02fe5ec2c31e7fe807f">
            {children}
          </CopilotKit>
        </ClientWrapper>
      </body>
    </html>
  );
}
